ChessSharp.Web/Controllers/HistoryController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Chess.Data.Entities;
using Chess.Domain.Repositories;
using ChessSharp.Web.Models;

namespace ChessSharp.Web.Controllers
{
    [Authorize]
    public class HistoryController : BaseController
    {
        private readonly GameRepository _gameRepository;

        public HistoryController()
        {
            _gameRepository = new GameRepository(UnitOfWork);
        }

        [HttpGet]
        public ActionResult Games(int? id = null)
        {
            if (CurrentUser != null)
            {
                var completedGames = _gameRepository.GetUserGames(CurrentUser)
                    .Where(g => g.Complete)
                    .OrderBy(g => g.Id)
                    .Reverse()
                    .ToList();

                var games = new List<CompletedGameViewModel>();

                foreach (var game in completedGames)
                {
                    var gameModel = AutoMapper.Mapper.Map<CompletedGameViewModel>(game);

                    if (game.WinnerPlayer != null)
                        gameModel.Win = false;
                    if (game.WinnerPlayer == CurrentUser)
                        gameModel.Win = true;

                    games.Add(gameModel);
                }

                return View(games);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Challenges(int? id = null)
        {
            if (CurrentUser != null)
            {
                var challenges = UnitOfWork.All<Challenge>(c => c.ChallengingPlayer == CurrentUser);

                return View(challenges);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

ChessSharp.Web/Views/Shared/_Layout.cshtml
@using ChessSharp.Web.Models
@using WebGrease.Css.Extensions

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Chess#</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/angular")

</head>
<body ng-app="csPlayChessApp">

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.Partial("_NotificationPartial")
                @Html.ActionLink("Chess#", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Challenge", "Make", "Challenge")</li>
                    <li>@Html.ActionLink("Game History", "Games", "History")</li>
                    <li>@Html.ActionLink("Challenge History", "Challenges", "History")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>



    <div class="container body-content">
        @RenderBody()
        <hr />

        <style>
            .player-status-list {
                float: right;
                display: inline-block;
            }
        </style>

        <footer>
            <p style="float: left;">&copy; @DateTime.Now.Year - Chess#</p>

        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>

ChessSharp.Web/Views/Shared/_NotificationPartial.cshtml
<link href="~/Content/Notification.css" rel="stylesheet" />

<div ng-controller="NotificationCtrl" class="player-status-list navbar-brand"
     style="padding: 0;
       margin: 0;
       margin-right: 5px;
       float: left;"
     ng-mouseout="handleMouseOut()">
    <span class="status-tab" ng-click="toggleNotifications()">
        <span ng-cloak>
            <span class="icon-count" ng-hide="challenges.length == 0">
                {{challenges.length}}
            </span>
            <span class="icon-count" ng-hide="readyGameCount() == 0">
                {{readyGameCount()}}
            </span>
        </span>
        <img src="~/Images/chess-notify.png" />
    </span>
    <div class="status-list" ng-hide="!showNotifications" ng-mouseout="handleMouseOut()" ng-mouseover="cancelMouseOut()" ng-cloak>
        <div class="challenges">
            <span ng-click="toggleChallenges();">
                Challenges
                <i class="glyphicon glyphicon-circle-arrow-down"></i>
                <span class="count">{{challenges.length}}</span>
            </span>
            <ul ng-show="showChallenges">
                <li ng-repeat="challenge in challenges">
                    <a href="~/Challenge/Decide/{{challenge.Id}}">
                        <h6>{{challenge.ChallengeTitle}}</h6>
                        {{challenge.Opponent.DisplayName}}
                    </a>
                </li>
                <li ng-hide="challenges.length > 0">
                    <a>No incoming challenges</a>
                </li>
            </ul>

        </div>

        <div class="games">
            <span ng-click="toggleGames()">
                Games
                <i class="glyphicon glyphicon-circle-arrow-down"></i>
                <span class="count">{{readyGameCount()}}</span>
            </span>
            <ul ng-show="showGames">
                <li ng-repeat="game in games">
                    <a href="~/Home/Play#/{{game.Id}}" ng-class="{ 'game-ready': game.IsPlayersTurn }">
                        <h6>{{game.Name}}</h6>
                        {{game.OpponentName}}
                    </a>
                </li>
                <li ng-hide="games.length > 0">
                    <a>No active games</a>
                </li>
            </ul>
        </div>
    </div>
</div>